name: Build Docker Image Run Host

on:
  push:
    tags:
      - "apitm-v*.*.*"  # 后面每次更新提交，只有打上tag之后才会进行发布更新，减少actions执行次数
      - "v*.*.*"  # 后面每次更新提交，只有打上tag之后才会进行发布更新，减少actions执行次数
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      # get image tag name
      - name: Get Image Tag Name
        run: |
          if [ x${{ github.event.inputs.tag }} == x"" ]; then
            echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: "${{ secrets.DOCKER_REGISTRY }}"
          region-id: "${{ secrets.DOCKER_REGISTRY_REGION }}"  # 3
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Deploy and Build Image
        run: |
          cd src/Api/Api.Template
          dotnet restore
          dotnet publish -c Release -o out
          cd bin/Release/net7.0
          docker build -t "${{ secrets.DOCKER_REGISTRY }}/ccdto/api.template:${{ env.TAG_NAME }}" -f Dockerfile .

      - name: Push Image
        run: |
          docker images
          docker push "${{ secrets.DOCKER_REGISTRY }}/ccdto/api.template:${{ env.TAG_NAME }}"