name: Build Api.Template Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: "${{ secrets.DOCKER_REGISTRY }}"
          region-id: "${{ secrets.DOCKER_REGISTRY_REGION }}"  # 3
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Deploy and Build Image
        run: |
          cd src/Api/Api.Template
          dotnet restore
          dotnet publish -c Release -o out
          cp Dockerfile bin/Release/net7.0
          cd bin/Release/net7.0
          docker build -t "${{ secrets.DOCKER_REGISTRY }}/ccdto/api.template:latest" -f Dockerfile .
          ls /home/runner/work/CCDto/CCDto/src/Api/DBConneciton/application
          ls /home/runner/work/CCDto/CCDto/src/Api/DBTable/application
          ls /home/runner/work/CCDto/CCDto/src/Api/DBField/application

      - name: Push Image
        run: |
          docker images
          docker push "${{ secrets.DOCKER_REGISTRY }}/ccdto/api.template:latest"

  call_api_dbconnection:
    needs: build
    uses: ./.github/workflows/api_connection.yml
    secrets: inherit

  call_api_dbtable:
    needs: build
    uses: ./.github/workflows/api_dbtable.yml
    secrets: inherit

  call_api_dbfield:
    needs: build
    uses: ./.github/workflows/api_dbfield.yml
    secrets: inherit
